### ISSUE TITLE
Error in print epoch_time: list index out of range

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/tCNNS-Project#4]
Branch: improve
Commands:
```bash
Singularity$ make -B build/tCNNS.sif
time singularity run --nv --bind `pwd`/tmp/:/candle_data_dir  build/tCNNS.sif train.sh 7 /candle_data_dir --epochs 1
...
2023-09-27 11:12:01.351483: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0:   N
2023-09-27 11:12:01.352731: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30581 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:b3:00.0, compute capability: 7.0)
epoch: 0, loss: 0.00547048 r2: -0.179316 pearson: 0.0558582 rmse: 0.0739627, spearman: 0.0468675
epoch with lowest val_loss: 0, loss: 0.00547048
rm: cannot remove '/candle_data_dir/tCNNS/Output/EXP000/RUN000/model/*': No such file or directory
Saved!
Total number of epochs: 1.
Best epoch with lowest val_loss: 0.
Traceback (most recent call last):
  File "/usr/local/tCNNS-Project/tcnns_baseline_tensorflow.py", line 363, in <module>
    main()
  File "/usr/local/tCNNS-Project/tcnns_baseline_tensorflow.py", line 357, in main
    run(gParameters)
  File "/usr/local/tCNNS-Project/tcnns_baseline_tensorflow.py", line 342, in run
    print(f"Runtime for first epoch: {epoch_time[0]}")
IndexError: list index out of range

real    0m37.125s
user    0m26.313s
sys     0m31.599s
```

**Comment by wilke** [comment]
This seems specific to `--epochs 1`

**Comment by jonesse3** [comment]
@wilke Updated the code on both develop and improve branch. Should work now for --epochs 1.
