### ISSUE TITLE
Unexpected keyword argument in csa_wf_v3.py

### ISSUE THREAD

**Issue by jonesse3** [JDACS4C-IMPROVE/tCNNS-Project#7]
Traceback (most recent call last):
  File "csa_wf_v3.py", line 199, in <module>
    result = subprocess.run(preprocess_run, capture_output=True, text=True, check=True)
  File "/homes/ac.sejones/miniconda3/envs/tcnns/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

**Comment by jonesse3** [comment]
Since tCNNS uses Python 3.6, some of the keyword arguments for _subprocess.run_ is not recognized. To quickly fix this issue, the code was modified to the following:

```
#result = subprocess.run(preprocess_run, capture_output=True, text=True, check=True)
result = subprocess.run(preprocess_run)
```
